### ISSUE TITLE
Update for Gnome 41

### ISSUE THREAD

**Issue by SP1966** [Cj-Malone/Fuzzy-Clock#1]
Title says it all, love the extension, hopefully it'll be updated!

**Comment by Cj-Malone** [comment]
Good to know somebody is using this.

I've just pushed a new version, seems to work although I haven't done a lot of testing.

You can get it [here](https://github.com/Cj-Malone/Fuzzy-Clock/releases/tag/v11) or [here](https://extensions.gnome.org/extension/1281/fuzzy-clock/).
