### ISSUE TITLE
Update for gnome 43?

### ISSUE THREAD

**Issue by confuzled** [Cj-Malone/Fuzzy-Clock#2]
love the kde fuzzy clock, wanted to use something similar on gnome but found out its not compatible with gnome 43

will this be updated for gnome 43?

**Comment by Cj-Malone** [comment]
If it's as 42, yes. If it needs a bunch of work, probably not, depends how annoyed I get without it.

**Comment by confuzled** [comment]
Just gonna mark as closed because of the pull request
